name: infra-az-hub-network

on:
  push:
    branches:
      - main
    paths:
      - "infra/az-hub-network/**"
      - ".github/workflows/infra-az-hub-network.yml"
  pull_request:
    paths:
      - "infra/az-hub-network/**"
      - ".github/workflows/infra-az-hub-network.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write

jobs:
  terraform:
    strategy:
      fail-fast: false
      matrix:
        env: [{ name: "hub-infra" }]
    uses: ./.github/workflows/template-terraform.yml
    with:
      working-dir: "infra/az-hub-network"
      environment: ${{ matrix.env.name }}
      backend-key: "az-hub-network"
      vars: |
        azure_subscription_id
        azure_tenant_id
        gh_runner_app_id
        gh_runner_app_private_key
    secrets: inherit