name: ui-landingapp
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ui-landingapp.yml"
      - "src/ui/landingapp/**"
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/ui-landingapp.yml"
      - "src/ui/landingapp/**"

permissions:
  contents: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  version-tag:
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.version-tag.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        id: version-tag
        uses: ./.github/actions/version-tag
        with:
          prefix: landingapp
          github-token: ${{ secrets.GITHUB_TOKEN }}

  docker:
    needs: [version-tag]
    uses: ./.github/workflows/template-docker.yml
    with:
      dockerfile: src/ui/landingapp/Dockerfile
      working-directory: src/ui/landingapp
      image_name: cobhubinfraweacr.azurecr.io/landingapp
      version: ${{ needs.version-tag.outputs.version }}
    secrets: inherit

  deploy:
    needs: [version-tag, docker]
    strategy:
      fail-fast: false
      matrix:
        env: [
          { name: "dev-app", infra: "stg-infra"},
          { name: "prd-app", infra: "stg-infra"}
        ]
    uses: ./.github/workflows/template-k8s-deploy.yml
    with:
      environment: ${{ matrix.env.name }}
      namespace: "cob-${{ matrix.env.name }}"
      app-name: "landingapp"
      image: ${{ needs.docker.outputs.image_name }}
      aks-cluster-name: "cob-aks"
      aks-resource-group: "cob-${{ matrix.env.infra }}-we-aks"    
      version-tag: "landingapp"
    secrets: inherit